version: '3.4'

services:
  limo:
    container_name: limo
    build:
      context: ./src
    image: ros:melodic-perception
    ports:
      - 8888:8888
    volumes:
      - $HOME/limo_data:/limo_data
    stdin_open: true
    tty: true
